rent_app/rent_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('properties/', include('rent_management.urls'))

]

rent_app/rent_management/urls.py
from django.urls import path, include
from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register(r'properties', views.PropertyViewSet, basename="property-api")
router.register(r'addresses', views.AddressViewSet, basename="address-api") # using just 'address' conflicts with path 'address-list bc router auto generates various urls
router.register(r'rentals', views.RentalViewSet, basename="rental-api")
router.register(r'tenants', views.TenantViewSet, basename="tenant-api")
router.register(r'finances', views.TotalTransactionsViewSet, basename="total-api")
router.register(r'payments', views.PaymentViewSet, basename="payment-api")
router.register(r'expenses', views.ExpenseViewSet, basename="expense-api")
router.register(r'users', views.UserViewSet, basename="users-api")

app_name = "rent_management"
urlpatterns = [
    path("", views.PropertyListView.as_view(), name='properties'),
    path("api/", include(router.urls)),
    path("create-property", views.create_property, name='property-create'),
    path("create-address", views.create_address, name='address-create'),
    path("view-address/", views.AddressListView.as_view(), name="address-list"),
    path("create-rental", views.create_rental, name="rental-create"),
    path("view-rentals/", views.RentalListView.as_view(), name="rental-list")
]

rent_app/rent_management/models.py
from django.db import models
from django.utils import timezone
from datetime import timedelta
from django import forms
from django.core.exceptions import ValidationError

from django.db.models import Sum

# for token authentication #
from rest_framework.authtoken.models import Token
from accounts.models import CustomUser


# Create your models here.
class Address(models.Model):
    class Meta:
        verbose_name_plural = "Addresses"   
    owner = models.ForeignKey(CustomUser, related_name="addresses", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    country = models.CharField(max_length=20,)
    state = models.CharField(max_length=20,)
    city = models.CharField(max_length=20,)
    line1 = models.CharField(max_length=50,)
    line2 = models.CharField(max_length=50, blank=True, null=True) 
    zipcode = models.CharField(max_length=10,)

    def __str__(self):
        return f"{self.line1}\n\
                 {self.line2}\n\
                 {self.city} {self.state} {self.zipcode}\n\
                 {self.country}"
    

# MAKE SURE PROPERTY CAN ONLY BE RENTED ONCE! IF STATUS == RENTED, CAN'T CREATE RENTAL WITH IT
class Property(models.Model):
    class Meta:
        verbose_name_plural = "Properties" # used to have Property show up in admin page as properties and not propertys
        ordering = ["owner"]

    PROPERTY_TYPE_CHOICES = (
        # left is actual value, right is shown value
        ('flat', 'Flat'),
        ('house', 'House'),
        ('condo', 'Condo'),
        ('shop', 'Shop'),
        ('townhouse', 'Townhouse'),
        ('bungalow', 'Bungalow'),
        ('other', 'Other')
    )
    PROPERTY_STATUS = (
        ('available', 'Available'),
        ('under service', 'Under Service'),
        ('unavailable', 'Unavailable'),
        ('sold out', 'Sold Out'),
        ('rented', 'Rented'),
    )
    BILLING_CYCLE = (
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
        ('quarterly', 'Quarterly'),
        ('annually', 'Anually'),
    )

    owner = models.ForeignKey(CustomUser, related_name="properties", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    property_type = models.CharField(max_length=15, choices=PROPERTY_TYPE_CHOICES)
    other_type = models.CharField(max_length=50, null=True, blank=True) # only show when type is "other" for manual input 
    name = models.CharField(max_length=200, unique=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, null=True, blank=True) # cascade used to prevent orhpans of address class
    is_active = models.BooleanField(default=True)
    description = models.CharField(max_length=50, null=True, blank=True)
    status = models.CharField(max_length=15, choices=PROPERTY_STATUS, default='available')
    payment_freq = models.CharField(max_length=9, choices=BILLING_CYCLE, default='monthly')
    default_rent = models.DecimalField(max_digits=7, decimal_places=2, default=0.00) # default rent bc could be different depending on contract
    
    def get_payment_freq(self):
        return self.payment_freq
    

    def __str__(self):
        return f"{self.name}: {self.property_type} - {self.get_status_display()}" 
        

class ReferencePerson(models.Model):
    owner = models.ForeignKey(CustomUser, related_name="reference_persons", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10, blank=True, null=True)
    phone_num = models.CharField(max_length=12, blank=True, null=True)
    email = models.EmailField(max_length=80, blank=True, null=True)
    relationship = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Tenant(models.Model):
    owner = models.ForeignKey(CustomUser, related_name="tenants", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    first_name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=10)
    phone_num = models.CharField(max_length=12, blank=True, null=True)
    email = models.CharField(max_length=80, blank=True, null=True)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, blank=True, null=True)
    reference = models.ForeignKey(ReferencePerson,on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Rental(models.Model):
    BILLING_CYCLE = (
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
        ('quarterly', 'Quarterly'),
        ('annually', 'Anually'),
    )
    owner = models.ForeignKey(CustomUser, related_name="rentals", on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)
    lease_start_date = models.DateField(default=timezone.now)
    lease_end_date = models.DateField(default=timezone.now() + timedelta(days=30))
    lease_duration = models.DurationField(blank=True, null=True, default=timedelta(days=30))
    rent = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    rental_freq = models.CharField(max_length=13, choices=BILLING_CYCLE, default="monthly")
    description = models.CharField(max_length=50, null=True, blank=True)

    def clean(self):
        # If lease start date greater than lease end date, set end date to start date plus lease duration
        if self.lease_start_date >= self.lease_end_date:
            self.lease_end_date = self.lease_start_date + self.lease_duration

        if self.property.status != "available":
            raise ValidationError("Only available properties can be rented!")

        super().clean()

    def save(self, *args, **kwargs):
        # Used to only set fields only when a new Rental instance is being created
        if not self.pk:
            self.property.status = "rented"

            if not self.rent:
                self.rent = self.property.default_rent
            self.property.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.property.status = "available"
        self.property.save()
        super().delete(*args, **kwargs)


    def __str__(self):
        return f"{self.property.name} - ({self.property.property_type}: {self.tenant.first_name} {self.tenant.last_name}: {self.property.status})"

class Expense(models.Model):
    REPAIR_TYPES = (
        ('general_repair', 'Repair'),
        ('electric_repair', 'Electric Repair'),
        ('other', 'Other')
    )
    rental = models.ForeignKey(Rental, on_delete=models.CASCADE, blank=False, null=True)
    owner = models.ForeignKey(CustomUser, related_name="expenses", on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    repair_type = models.CharField(max_length=20, choices=REPAIR_TYPES, default='expenses')
    payment_amount = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    date_paid = models.DateField(default=timezone.now().date())
    description = models.CharField(max_length=50, blank=True, null=True)


    @classmethod
    def get_total_expenses(cls):
        total_count = cls.objects.count()
        if total_count == 0:
            return 0
        
        total = Expense.objects.aggregate(Sum("payment_amount"))["payment_amount__sum"]
        return total
        

    def save(self, *args, **kwargs):
        if self.rental:
            self.property = self.rental.property
        super().save(*args, **kwargs)

    def clean(self):
        if not self.property:
            self.property = self.rental.property
        super().clean()

    def __str__(self):
        return f"{self.rental} ({self.repair_type} cost ${self.payment_amount})"

class Payment(models.Model):
    owner = models.ForeignKey(CustomUser, related_name="payments", on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    rental = models.ForeignKey(Rental, on_delete=models.CASCADE)
    payment_amount = models.DecimalField(default=0.00, decimal_places=2, max_digits=10)
    date_paid = models.DateField(default=timezone.now().date())
    description = models.CharField(max_length=50, blank=True, null=True)

    @classmethod
    def get_total_payments(cls) -> float:
        """
        Returns total payments as a decimal
        """
        total_count = cls.objects.count()
        if total_count == 0:
            return 0
        
        total = cls.objects.aggregate(Sum("payment_amount"))["payment_amount__sum"]
        return total
    
    def clean(self):
        if not self.property:
            self.property = self.rental.property

        super().clean()

    def save(self, *args, **kwargs):
        if self.rental:
            self.property = self.rental.property
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.rental} (profit ${self.payment_amount})"

rent_app/rent_management/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_list_or_404, redirect, get_object_or_404
from django.urls import reverse
from django.views import generic
from .forms import PropertyCreateForm, AddressCreateForm, RentalCreateForm
from django.db import transaction

from .models import Property, Address, Rental, Tenant, Payment, Expense

#### for Django Rest Framework
from .serializers import *
from rest_framework import viewsets, status
from rest_framework.response import Response
from rest_framework.serializers import ValidationError
from rest_framework.schemas import get_schema_view
from rest_framework import permissions

### permissions.py for development and production ###
from .permissions import DevelopmentModelPermission, get_custom_permissions
from accounts.models import CustomUser

class PropertyListView(generic.ListView):
    template_name = "rent_management/property_list.html"
    context_object_name = "properties"

    def get_queryset(self):
        properties = Property.objects.all()
        return properties
    
    def get_permissions(self):
        return get_custom_permissions(self.request)
    
class AddressListView(generic.ListView):
    template_name = "rent_management/address_list.html"
    context_object_name = "addresses"
    
    def get_queryset(self):
        addresses = Address.objects.all()
        return addresses
    
    def get_permissions(self):
        return get_custom_permissions(self.request)
    
class RentalListView(generic.ListView):
    template_name = "rent_management/rental_list.html"
    context_object_name = "rentals"

    def get_queryset(self):
        rentals = Rental.objects.all()
        return rentals
    
    def get_permissions(self):
        return get_custom_permissions(self.request)
    
def create_rental(request):
    if request.method == "POST":
        form = RentalCreateForm(request.POST)
        if form.is_valid():
            rental = form.save(commit=False) # don't save yet

            #get property and tenant IDs
            property_id = form.cleaned_data['property'].id
            tenant_id = form.cleaned_data['tenant'].id

            rental.property = Property.objects.get(id=property_id)
            rental.tenant = Tenant.objects.get(id=tenant_id)
            rental.lease_duration = rental.lease_end_date - rental.lease_start_date

            # set property status to 'rented' during rental creation
            if rental.property.status != "rented":
                rental.property.status = "rented"
                rental.property.save()

            rental.rent = rental.property.default_rent

            rental.save()
            return redirect("rent_management:properties")
    else:
        form = RentalCreateForm()
    
    return render(request, "rent_management/rental_create.html", {"form": form})
 
def create_property(request):
    if request.method == 'POST':
        form = PropertyCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('rent_management:properties')
    else:
        form = PropertyCreateForm()
    
    return render(request, 'rent_management/property_create.html', {'form': form})

def create_address(request):
    if request.method == 'POST':
        form = AddressCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("rent_management:properties")
    else:
        form = AddressCreateForm()
    
    return render(request, 'rent_management/address_create.html', {'form': form})
    

class UserViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = CustomUser.objects.all()
    serializer_class = UserSerializer

class PropertyViewSet(viewsets.ModelViewSet):
    # DRF view handles the API requests
    queryset = Property.objects.all()
    serializer_class = PropertySerializer

    def get_permissions(self):
        return get_custom_permissions(self.request)
    
    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)


class AddressViewSet(viewsets.ModelViewSet):
    queryset = Address.objects.all()
    serializer_class = AddressSerializer

    def get_permissions(self):
        return get_custom_permissions(self.request)
    
    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

class RentalViewSet(viewsets.ModelViewSet):
    queryset = Rental.objects.all()
    serializer_class = RentalSerializer

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)
            
    def perform_destroy(self, instance):
        instance.property.status = "available"
        instance.property.save()
        instance.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
    
    def get_permissions(self):
        return get_custom_permissions(self.request)
    
class TenantViewSet(viewsets.ModelViewSet):
    queryset = Tenant.objects.all()
    serializer_class = TenantSerializer

    def get_permissions(self):
        return get_custom_permissions(self.request)
    
    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

class PaymentViewSet(viewsets.ModelViewSet):
    queryset = Payment.objects.all()
    serializer_class = PaymentSerializer

    def get_permissions(self):
        return get_custom_permissions(self.request)
    
    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)
    
class ExpenseViewSet(viewsets.ModelViewSet):
    queryset = Expense.objects.all()
    serializer_class = ExpenseSerializer

    def get_permissions(self):
        return get_custom_permissions(self.request)
    
    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

class TotalTransactionsViewSet(viewsets.ModelViewSet):
    queryset = None
    serializer_class = TotalTransactionSerializer

    def get_permissions(self):
        return get_custom_permissions(self.request)
    
    def list(self, request):
        total_payments = Payment.get_total_payments()
        total_expenses = Expense.get_total_expenses()

        serializer = TotalTransactionSerializer(data={
            "total_payments": total_payments,
            "total_expenses": total_expenses,
        })
        
        serializer.is_valid()
        return Response(serializer.data)
    
    # viewset only used for fetching total finiances, DO NOT ALLOW MODIFICATIONS, no 'create' method

rent_app/rent_management/templates/rent_management/address_create.html
<!DOCTYPE html>
<html>
    <head>
        <title>Create Address</title>
    </head>
    <body>
        <h1>Add an address below</h1>
        <form method="POST">
            {% csrf_token %} {{ form.as_p }} <button type="submit">Create address</button>
            <a href="{% url 'rent_management:properties' %}"><button>View all properties</button></a>
        </form>
    </body>
</html>

rent_app/rent_management/templates/rent_management/address_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Address Details</title>
</head>
<body>
    <h1>Address</h1>
    <ul>
        {% for address in addresses %}
            <p><strong>Country:</strong> {{ address.country }}</p>
            <p><strong>State:</strong> {{ address.state }}</p>
            <p><strong>City:</strong> {{ address.city }}</p>
            <p><strong>Address Line 1:</strong> {{ address.line1 }}</p>
            {% if address.line2 %}
                <p><strong>Address Line 2:</strong> {{ address.line2 }}</p>
            {% endif %}
            <p><strong>Zipcode:</strong> {{ address.zipcode }}</p>
        {% endfor %}
    </ul>
    <a href="{% url 'rent_management:properties' %}"><button>View all properties</button></a>
    <a href="{% url 'rent_management:address-create' %}"><button>Add new address</button></a>

</body>
</html>

rent_app/rent_management/templates/rent_management/property_create.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Create Property</title>
    <link rel="stylesheet" href="style.css"> 
</head>
<body>
    <h1>Create New Property</h1>
    <form method="post">
        {% csrf_token %}  {{ form.as_p }}   <button type="submit">Create</button>
        <a href="{% url 'rent_management:properties' %}"><button>View all properties</button></a>
    </form>
</body>
</html>

rent_app/rent_management/templates/rent_management/property_list.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Property Listings</title>
    <link rel="stylesheet" href="style.css">  </head>
<body>
    <h1>All Properties</h1>

    <ul>
        {% for property in properties %}
            <li>
                <h2>{{ property.name }}</h2>
                <p><strong>ID</strong> ({{ property.id }})</p>
                <p><strong>Type:</strong> {{ property.type.capitalize }} 
                    {% if property.type == None %}
                        ({{ property.other_type }})
                    {% endif %}
                </p>
                <p><strong>Status:</strong> {{ property.get_status_display }}</p>
                <p><strong>Address:</strong> {{ property.address }}</p>  
                {% if property.description %}
                    <p><strong>Description:</strong> {{ property.description }}</p> 
                {% endif %}
                <p><strong>Payment Frequency:</strong> {{ property.get_payment_freq_display }}</p>
            </li>
        {% endfor %}
    </ul>
</body>
    <a href="{% url 'rent_management:property-create' %}"><button>Create property</button></a>
    <a href="{% url 'rent_management:address-create' %}"><button>Create address</button></a>
    <a href="{% url 'rent_management:address-list' %}"><button>View all addresses</button></a>
    <a href="{% url 'rent_management:rental-create' %}"><button>Create rental</button></a>
    <a href="{% url 'rent_management:rental-list' %}"><button>View rentals</button></a>
</html>

rent_app/rent_management/templates/rent_management/rental_create.html
<!DOCTYPE html>
<html>
<head>
    <title>Create Rental</title>
    <link rel="stylesheet" href="style.css"> 
</head>
<body>
    <h1>Create Rental</h1>

    <form method="POST">
        {% csrf_token %} 

        {% for field in form %}  
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                {{ field }}
            </div>
        {% endfor %}

        <button type="submit">Create Rental</button>
    </form>

    <a href="{% url 'rent_management:properties' %}"><button>View Properties</button></a>
</body>
</html>

rent_app/rent_management/templates/rent_management/rental_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Rental List</title>
    <link rel="stylesheet" href="style.css"> 
</head>

<body>
    <h1>My Rentals</h1>

    {% if rentals %} 
        <ul>
            {% for rental in rentals %}
                <li>
                    Property: {{ rental.property.name }} <br>
                    Tenant: {{ rental.tenant.first_name }} {{ rental.tenant.last_name }} <br>
                    Lease Period: {{ rental.lease_start_date }} - {{ rental.lease_end_date }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>You don't have any rentals yet.</p>
    {% endif %}

    <a href="{% url 'rent_management:rental-create' %}"><button>Create New Rental</button></a>
    <a href="{% url 'rent_management:properties' %}"><button>View all properties</button></a>
</body>
</html>